apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
        - containerPort: 16686  # UI
        - containerPort: 14250  # Model used by collector
        - containerPort: 14268  # HTTP accept directly from clients
        - containerPort: 6831   # Accept jaeger.thrift in compact Thrift protocol over UDP
          protocol: UDP
        - containerPort: 6832   # Accept jaeger.thrift in binary Thrift protocol over UDP
          protocol: UDP
        - containerPort: 9411   # Zipkin
        - containerPort: 4317        
        - containerPort: 4318
        env:
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: ":9411"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  ports:
  - name: ui
    port: 16686
    targetPort: 16686
  - name: collector-grpc
    port: 14250
    targetPort: 14250
  - name: collector-http
    port: 14268
    targetPort: 14268
  - name: agent-compact
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: agent-binary
    port: 6832
    protocol: UDP
    targetPort: 6832
  - name: zipkin
    port: 9411
    targetPort: 9411
  - name: http
    port: 4317
    targetPort: 4317 
  - name: grpc
    port: 4318
    targetPort: 4318     
  type: ClusterIP