apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
spec:
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - name: app
        image: fabriciosveronez/app-telemetria:v1	
        resources: {}
        ports:
        - containerPort: 8000
        env:
        - name: APP_NAME
          value: app-a
        - name: APP_URL_DESTINO
          value: http://app-b:8000
        - name: APP_ERRORS
          value: "5"
        - name: APP_LATENCY
          value: "100"                             
        - name: OTLP_ENDPOINT
          value: "http://otel-collector-opentelemetry-collector:4318" 
---
apiVersion: v1
kind: Service
metadata:
  name: app-a
spec:
  selector:
    app: app-a
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30001
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
spec:
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
    spec:
      containers:
      - name: app
        image: fabriciosveronez/app-telemetria:v1	
        resources: {}
        ports:
        - containerPort: 8000
        env:
        - name: APP_NAME
          value: app-b
        - name: APP_URL_DESTINO
          value: http://app-c:8000
        - name: APP_ERRORS
          value: "10"
        - name: APP_LATENCY
          value: "150"                             
        - name: OTLP_ENDPOINT
          value: "http://otel-collector-opentelemetry-collector:4318" 
---
apiVersion: v1
kind: Service
metadata:
  name: app-b
spec:
  selector:
    app: app-b
  ports:
  - port: 8000
    targetPort: 8000
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-c
spec:
  selector:
    matchLabels:
      app: app-c
  template:
    metadata:
      labels:
        app: app-c
    spec:
      containers:
      - name: app
        image: fabriciosveronez/app-telemetria:v1	
        resources: {}
        ports:
        - containerPort: 8000
        env:
        - name: APP_NAME
          value: app-c
        - name: APP_ERRORS
          value: "15"
        - name: APP_LATENCY
          value: "200"                             
        - name: OTLP_ENDPOINT
          value: "http://otel-collector-opentelemetry-collector:4318"  
---
apiVersion: v1
kind: Service
metadata:
  name: app-c
spec:
  selector:
    app: app-c
  ports:
  - port: 8000
    targetPort: 8000
